# Generated by Django 4.2.3 on 2023-07-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="Tashkent, Uzbekistan", max_length=100),
        ),
    ]
