# Generated by Django 4.2.3 on 2023-07-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
