# Generated by Django 4.2.3 on 2023-07-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="Your Bio", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(default="Your Location", max_length=100),
        ),
    ]
