# Generated by Django 4.2.3 on 2023-07-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_bio_alter_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="Your Bio"),
        ),
    ]
