# Generated by Django 4.2.3 on 2023-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="Your Bio", max_length=400),
        ),
    ]
