# Generated by Django 4.2.3 on 2023-08-01 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default="4", on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
    ]
