# Generated by Django 4.2.3 on 2023-08-01 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
