# Generated by Django 4.2.3 on 2023-08-01 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_comment_date_posted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date_edited",
        ),
    ]
