# Generated by Django 4.2.3 on 2023-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_remove_post_date_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=100),
        ),
    ]
