# Generated by Django 4.2.3 on 2023-08-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="blog_post.jpg", upload_to="post_pics"),
        ),
    ]
